### ISSUE TITLE
Publish v0.1.0

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vtvalidate#11]
Now that the dust has settled around the `v0.1.0-alpha` dev release, time to get [an official `v0.1.0` release/tag out](https://github.com/mapbox/node-cpp-skel/blob/master/docs/publishing-binaries.md).

cc @springmeyer @millzpaugh

**Comment by springmeyer** [comment]
https://github.com/mapbox/vtvalidate/releases/tag/v0.2.0 is now out 🎉, so closing. Changelog has the details: https://github.com/mapbox/vtvalidate/blob/master/CHANGELOG.md
