### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtvalidate#13]
It would be neat have a /bin/vtvalidate command for local debugging!

cc @GretaCB

**Comment by springmeyer** [comment]
I had the same idea! https://github.com/mapbox/vtvalidate/pull/2  PR got behind so I need to rebase again and add tests.

**Comment by mapsam** [comment]
Oh wow, totally missed that PR - nice!

**Comment by mapsam** [comment]
Also, anyone is welcome to call me out on the issue title: 

> Command Line Interface Interface

**Comment by GretaCB** [comment]
Happy to take care of the rebase @springmeyer .

**Comment by springmeyer** [comment]
👍  sounds good @GretaCB - if it is too tricky feel free to totally recreate/drop my commits/start from scratch.

**Comment by GretaCB** [comment]
Closing per https://github.com/mapbox/vtvalidate/pull/16
