### ISSUE TITLE
Fresh clone + make raises an error

### ISSUE THREAD

**Issue by MattFerraro** [mapbox/vtvalidate#27]
On mac high sierra, on a fresh git clone with
```
~/Documents/git/vtvalidate$ node --version
v11.5.0
```
the `make` command crashes with:
```
../src/vtvalidate.cpp:177:48: error: 'ToObject' is deprecated: Use maybe version [-Werror,-Wdeprecated-declarations]
    v8::Local<v8::Object> buffer = buffer_val->ToObject();
                                               ^
/Users/matthew/.node-gyp/11.5.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/matthew/.node-gyp/11.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
```

Expected behavior is that running `make` doesn't crash. Can others repro?

**Comment by mapsam** [comment]
@MattFerraro thanks for reporting! Looks like a NAN deprecation warning that is failing the build. I'll go ahead and add the deprecation flags to just throw a warning and not fail in the build step. 

Long-term perhaps @artemp can start looking at porting this module over to N-API?

**Comment by mapsam** [comment]
@MattFerraro the `-Wno-error=deprecated-declarations` is now a part of master (and in a 0.2.3 release) so you should be able to build from master if you pull
