### ISSUE TITLE
Troubleshoot Node 6 install failure

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vtvalidate#5]
Per https://travis-ci.org/mapbox/mapbox-tile-copy/jobs/319979520#L1206 as part of https://github.com/mapbox/mapbox-tile-copy/pull/114, Travis is failing on _Node 6_ jobs for upstream lib using vtvalidate as a dep.

```
npm ERR! enoent ENOENT: no such file or directory, rename '/dev/mapbox-tile-copy/node_modules/.staging/abbrev-1180bf43'
```

- Able to replicate the same error locally, when using Node 6 to `npm install` (npm 3.10.10)
  - Travis is using: node `v6.12.2` and npm `v3.10.10`
- Removing package-lock does nothing
- Clearing cache does nothing (`npm cache clean --force`)
- Other relevant tickets:
  - https://github.com/mapbox/node-sqlite3/issues/866

Will post findings here as I continue to troubleshoot.

cc @mapbox/core-tech

**Comment by GretaCB** [comment]
**Update**
- Was able to successfully install mapbox-tile-copy deps (including vtvalidate) by updating my local env to use nvm 5. I also noticed that when switching between Node version using `nvm` causes the `npm` version to oscillate, which I didnt realize before. Currently looking into bumping Travis to npm 5

**Comment by GretaCB** [comment]
Bumping to `npm 5` did the trick 👍 . Closing.

**Comment by springmeyer** [comment]
Just catching up here. Awesome work on figuring out a fix here @GretaCB
